baseURL: "https://doubleivan.ru/"
author:
  name: "Ivan Chernov, Ivan Elfimov"
  email: "ivan.elfimov@ostrovok.ru"
languageCode: "ru-ru"
title: "Два Ивана"
theme: "DoubleIvan"

menu:
  main:
    - identifier: podcasts
      name: Подкасты
      url: /podcasts/
      weight: 10

params:
  title: "Два Ивана (название обсуждается)"
  description: "Разработчики из Ostrovok.ru разговаривают про Python и IT"
  podcast_copyright: "Creative Commons - Attribution-NonCommercial-NoDerivatives 4.0 International (CC BY-NC-ND 4.0) License."
  email: "ivan.elfimov@ostrovok.ru"
  homeInfoParams:
    enabled: true
    Title: "Два Ивана (название обсуждается)"
    Content: "Разработчики из Ostrovok.ru разговаривают про Python и IT"

  socialIcons:
    - name: "rss"
      url: "https://doubleivan.ru/podcasts/index.xml"
    - name: "github"
      url: "https://github.com/biozz/doubleivan.ru"
    - name: "yandex_music"
      url: "https://music.yandex.ru/album/26457076"
